<?php

#program/api/report

//引入User类文件
include_class("User");
//实例化User类
$User=new User();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

//补全预处理参数
if(empty($_POST['app_id']))
    $_POST['app_id']="";
if(getPermission($_POST['app_id'],'api_report')==='Y')
{
    if(empty($_GET['from']))
    {
        $result_code=1009;
        $result_content='from没有指定目标';
        $result['array']['api']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {
        if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp']))||empty($_POST['reason']))
        {
            $result_code=1011;
            $result_content='必要参数为空';
            $result['array']['api']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
        else
        {
            //取qq和微信号
            $qq=empty($_POST['qq'])?'':$_POST['qq'];
            $wechat=empty($_POST['wechat'])?'':$_POST['wechat'];

            //补齐不必要参数
            if(empty($_POST['time']))
                $_POST['time']='';
            if(empty($_POST['time_stamp']))
                $_POST['time_stamp']='';
            //取时间戳
            if(!empty($_POST['time_stamp']))
            $time=$_POST['time_stamp'];
            else
            $time=strtotime($_POST['time']);
            settype($time,'int');

            //判断时差是否在规定时间内
            if(time()-$time<=5*60&&time()-$time>=-(5*60))
            {
                if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
                {
                    if(empty($_FILES["file"])||$_FILES["file"]["error"]>0)
                    {
                        $result_code=1017;
                        $result_content='文件上传失败';
                        $result['array']['api']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        $file_zip_path=$_FILES["file"]["tmp_name"];
                        $file_zip=new ZipArchive();
                        if($file_zip->open($file_zip_path)===true&&filesize($file_zip_path)<5*1024*1024)
                        {
                            $file_zip->close();
                            //压缩包合法执行内容
                            //判断接口环境
                            if($_GET['from']==='app')
                            {
                                if(empty($_POST['uuid'])||empty($_POST['imei'])||empty($_POST['ukey'])||!(!empty($_POST['qq'])||!empty($_POST['wechat'])))
                                {
                                    $result_code=1011;
                                    $result_content='必要参数为空';
                                    $result['array']['api']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                                else
                                {
                                    //app环境下参数正常时执行
                                    //app签名
                                    $server_variable=array(
                                        'from'=>$_GET['from'],
                                        'app_id'=>$_POST['app_id'],
                                        'nonce'=>$_POST['nonce'],
                                        'time'=>$_POST['time'],
                                        'time_stamp'=>$_POST['time_stamp'],
                                        'imei'=>$_POST['imei'],
                                        'qq'=>$qq,
                                        'wechat'=>$wechat,
                                        'reason'=>$_POST['reason'],
                                        'uuid'=>$_POST['uuid'],
                                        'ukey'=>$_POST['ukey']
                                    );
                                    $server_sign='';
                                    foreach($server_variable as $key=>$value)
                                    {
                                        $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                                    }
                                    $app_key=getAppkey($_POST['app_id']);
                                    if(empty($app_key))
                                    {
                                        $result_code=1013;
                                        $result_content='非法请求';
                                        $result['array']['api']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>""
                                        );
                                        $result['exit']=1;
                                    }
                                    else
                                    {
                                        $server_sign.='&app_key='.getSignString($app_key);
                                        $server_sign=md5($server_sign);
                                        if($server_sign===$_POST['sign'])
                                        {
                                            //app签名验证通过
                                            //存储数据
                                            $file_zip_path="uploads/".(time().getRandomstring(12));
                                            move_uploaded_file($_FILES["file"]["tmp_name"],$file_zip_path);
                                            $server_time_stamp=time();
                                            //抛弃超过系统最大存储空间的数据
                                            $_POST['reason']=mb_substr($_POST['reason'],0,1024);
                                            //设置必要参数
                                            $User->app_id=$_POST['app_id'];
                                            $User->database_object=$Database;
                                            //设置uuid和ukey
                                            $User->setUuid($_POST['uuid']);
                                            $User->setUkey($_POST['ukey']);
                                            //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                                            $User->getUserInfo();
                                            //验证用户是否登录成功
                                            if($User->user_info['get'])
                                            {
                                                //写入数据库
                                                $table_name=$Database->getTablename('api_report_info_app');
                                                $sql_statement=$Database->object->prepare("INSERT INTO {$table_name}(app_id,time_stamp,qq,wechat,uuid,imei,refrom,reason,filepath) VALUES (:app_id,:time_stamp,:qq,:wechat,:uuid,:imei,:refrom,:reason,:filepath)");
                                                $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                                $sql_statement->bindParam(':time_stamp',$server_time_stamp);
                                                $sql_statement->bindParam(':qq',$_POST['qq']);
                                                $sql_statement->bindParam(':wechat',$_POST['wechat']);
                                                $sql_statement->bindParam(':uuid',$_POST['uuid']);
                                                $sql_statement->bindParam(':imei',$_POST['imei']);
                                                $sql_statement->bindParam(':refrom',$_GET['from']);
                                                $sql_statement->bindParam(':reason',$_POST['reason']);
                                                $sql_statement->bindParam(':filepath',$file_zip_path);
                                                if($sql_statement->execute())
                                                {
                                                    $result_code=0;
                                                    $result_content='已成功举报';
                                                    $result['array']['api']=array(
                                                        'title'=>"成功",
                                                        'content'=>$result_content,
                                                        'code'=>$result_code,
                                                        'variable'=>"请等待审核"
                                                    );
                                                }
                                                else
                                                {
                                                    $result_code=1018;
                                                    $result_content='异常错误';
                                                    $result['array']['api']=array(
                                                        'title'=>"失败",
                                                        'content'=>$result_content,
                                                        'code'=>$result_code,
                                                        'variable'=>""
                                                    );
                                                    $result['exit']=1;
                                                }
                                            }
                                            else
                                            {
                                                $result['array']['api']=$User->error_info['getUserInfo'];
                                                $result['exit']=1;
                                            }    
                                        }
                                        else
                                        {
                                            $result_code=1014;
                                            $result_content='非法请求';
                                            $result['array']['api']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>$_POST['sign']
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                }
                            }
                            else
                            {
                                $result_code=1010;
                                $result_content='from指定目标不合法';
                                $result['array']['api']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_GET['from']
                                );
                                $result['exit']=1;
                            }
                        }
                        else
                        {
                            unlink($file_zip_path);
                            $result_code=1016;
                            $result_content='压缩包不合法';
                            $result['array']['api']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else
                {
                    $result_code=1015;
                    $result_content='请求已过期';
                    $result['array']['api']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>""
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1012;
                $result_content='请求已过期';
                $result['array']['api']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
    }
}
else
{
    $result_code=10000;
    $result_content='无权调用接口';
    $result['array']['api']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>''
    );
    $result['exit']=1;
}
?>