<?php

#program/api/retrieve

//引入邮件配置
include_once 'config/mail.php';

//补全预处理参数
if(empty($_POST['app_id']))
    $_POST['app_id']="";
if(getPermission($_POST['app_id'],'api_userinfo')==='Y')
{
    if(empty($_GET['from']))
    {
        $result_code=1009;
        $result_content='from没有指定目标';
        $result['array']['api']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {
        if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
        {
            $result_code=1011;
            $result_content='必要参数为空';
            $result['array']['api']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
        else
        {
            //补齐不必要参数
            if(empty($_POST['time']))
                $_POST['time']='';
            if(empty($_POST['time_stamp']))
                $_POST['time_stamp']='';
            //取时间戳
            if(!empty($_POST['time_stamp']))
            $time=$_POST['time_stamp'];
            else
            $time=strtotime($_POST['time']);
            settype($time,'int');

            //判断时差是否在规定时间内
            if(time()-$time<=5*60&&time()-$time>=-(5*60))
            {
                if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
                {
                    //判断接口环境
                    if($_GET['from']==='email')
                    {
                        if((empty($_POST['email'])&&empty($_POST['user']))||empty($_POST['imgid'])||empty($_POST['code_value']))
                        {
                            $result_code=1011;
                            $result_content='必要参数为空';
                            $result['array']['api']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            //email环境下参数正常时执行
                            //补全不必要参数
                            if(empty($_POST['email']))
                                $_POST['email']='';
                            if(empty($_POST['user']))
                                $_POST['user']='';
                            //email签名
                            $server_variable=array(
                                'from'=>$_GET['from'],
                                'app_id'=>$_POST['app_id'],
                                'nonce'=>$_POST['nonce'],
                                'time'=>$_POST['time'],
                                'time_stamp'=>$_POST['time_stamp'],
                                'email'=>$_POST['email'],
                                'user'=>$_POST['user'],
                                'imgid'=>$_POST['imgid'],
                                'code_value'=>$_POST['code_value']
                            );
                            $server_sign='';
                            foreach($server_variable as $key=>$value)
                            {
                                $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                            }
                            $app_key=getAppkey($_POST['app_id']);
                            if(empty($app_key))
                            {
                                $result_code=1013;
                                $result_content='非法请求';
                                $result['array']['api']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>""
                                );
                                $result['exit']=1;
                            }
                            else
                            {
                                $server_sign.='&app_key='.getSignString($app_key);
                                $server_sign=md5($server_sign);
                                if($server_sign===$_POST['sign'])
                                {
                                    //email签名验证通过
                                    //验证imgid是否已过期,未过期刷新验证码并给出图片验证码
                                    $server_time_stamp=time();
                                    $table_name=$Database->getTablename('temporary_verifycode');
                                    $sql_statement=$Database->object->prepare("SELECT time_stamp,code_value FROM {$table_name} WHERE imgid=:imgid ORDER BY id DESC LIMIT 0,1");
                                    $sql_statement->bindParam(':imgid',$_POST['imgid']);
                                    $sql_statement->execute();
                                    $result_sql_temp=$sql_statement->fetch();
                                    if(isset($result_sql_temp['time_stamp'])&&$server_time_stamp<=$result_sql_temp['time_stamp']+3*60*60)
                                    {
                                        //销毁本次imgid值
                                        $sql_statement=$Database->object->prepare("DELETE FROM {$table_name} WHERE imgid=:imgid");
                                        $sql_statement->bindParam(':imgid',$_POST['imgid']);
                                        $sql_statement->execute();
                                        if(!empty($result_sql_temp['code_value'])&&$result_sql_temp['code_value']===$_POST['code_value'])
                                        {
                                            if((isEmail($_POST['email'])&&strlen($_POST['email'])<=$main_config['user_info']['email_len_max'])||$_POST['email']==='')
                                            {
                                                //抛弃超过系统最大存储空间的数据
                                                $_POST['email']=substr($_POST['email'],0,32);
                                                $_POST['user']=substr($_POST['user'],0,32);

                                                //否存在对应的用户
                                                $table_name=$Database->getTablename('user');
                                                if($_POST['email']!='')
                                                {
                                                    //查询邮箱
                                                    $sql_statement=$Database->object->prepare("SELECT uuid,id,user,nickname,proving,time_stamp,email FROM {$table_name} WHERE email=:email AND proving=1 ORDER BY id DESC LIMIT 0,1");
                                                    $sql_statement->bindParam(':email',$_POST['email']);
                                                }
                                                else
                                                {
                                                    //查询用户
                                                    $sql_statement=$Database->object->prepare("SELECT uuid,id,user,nickname,proving,time_stamp,email FROM {$table_name} WHERE user=:user AND proving=1 ORDER BY id DESC LIMIT 0,1");
                                                    $sql_statement->bindParam(':user',$_POST['user']);
                                                }
                                                $sql_statement->execute();
                                                $result_sql_temp=$sql_statement->fetch();
                                                if(isset($result_sql_temp['uuid']))
                                                {
                                                    //查询到存在该用户
                                                    $reid=getRandstringid();
                                                    $content_array=array(
                                                        "\${title}"=>"用户验证",
                                                        "\${organization}"=>$main_config['organization_config']['name'],
                                                        "\${date}"=>$ban_date=date("Y-m-d H:i:s",$server_time_stamp),
                                                        "\${user_name}"=>$result_sql_temp['user'],
                                                        "\${url}"=>$main_config['html_config']['protocol']."://".$main_config['html_config']['domain']."/?class=retrieve&mode=confirm&uuid={$result_sql_temp['uuid']}&reid={$reid}",
                                                        "\${overdue_date}"=>date("Y-m-d H:i:s",$server_time_stamp+7*24*60*60)
                                                    );
                                                    $ret_mail=$Sendmail->send("账户找回验证",$result_sql_temp['email'],"default/retrieve",$content_array);
                                                    if($ret_mail===1)
                                                    {
                                                        $table_name=$Database->getTablename('temporary_retrieve_user');
                                                        //删除之前的申请
                                                        $sql_statement=$Database->object->prepare("DELETE FROM {$table_name} WHERE email=:email");
                                                        $sql_statement->bindParam(':email',$result_sql_temp['email']);
                                                        $sql_statement->execute();
                                                        //存储本次申请纪录,不判断是否成功
                                                        $sql_statement=$Database->object->prepare("INSERT INTO {$table_name}(time_stamp,user,uuid,email,app_id,reid) VALUES (:time_stamp,:user,:uuid,:email,:app_id,:reid)");
                                                        $sql_statement->bindParam(':time_stamp',$server_time_stamp);
                                                        $sql_statement->bindParam(':user',$result_sql_temp['user']);
                                                        $sql_statement->bindParam(':uuid',$result_sql_temp['uuid']);
                                                        $sql_statement->bindParam(':email',$result_sql_temp['email']);
                                                        $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                                        $sql_statement->bindParam(':reid',$reid);
                                                        $sql_statement->execute();

                                                        $result_code=0;
                                                        $result_content='已申请找回密码';
                                                        $result['array']['api']=array(
                                                            'title'=>"成功",
                                                            'content'=>$result_content,
                                                            'code'=>$result_code,
                                                            'variable'=>"请前往邮箱验证"
                                                        );
                                                    }
                                                    else
                                                    {
                                                        $result_code=1019;
                                                        $result_content='邮件发送失败';
                                                        $result['array']['api']=array(
                                                            'title'=>"失败",
                                                            'content'=>$result_content,
                                                            'code'=>$result_code,
                                                            'variable'=>$ret_mail
                                                        );
                                                    }
                                                
                                                }
                                                else
                                                {
                                                    $result_code=1058;
                                                    $result_content='用户异常';
                                                    $result['array']['api']=array(
                                                        'title'=>"失败",
                                                        'content'=>$result_content,
                                                        'code'=>$result_code,
                                                        'variable'=>''
                                                    );
                                                    $result['exit']=1;
                                                }
                                            }
                                            else
                                            {
                                                $result_code=1022;
                                                $result_content='邮箱不合法';
                                                $result['array']['api']=array(
                                                    'title'=>"失败",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>$_POST['email']
                                                );
                                                $result['exit']=1;
                                            }
                                        }
                                        else
                                        {
                                            $result_code=1034;
                                            $result_content='验证码错误';
                                            $result['array']['api']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>""
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result_code=1033;
                                        $result_content='请求已过期';
                                        $result['array']['api']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>""
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result_code=1014;
                                    $result_content='非法请求';
                                    $result['array']['api']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>$_POST['sign']
                                    );
                                    $result['exit']=1;
                                }
                            }
                        }
                    }
                    else
                    {
                        $result_code=1010;
                        $result_content='from指定目标不合法';
                        $result['array']['api']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>$_GET['from']
                        );
                        $result['exit']=1;
                    }
                }
                else
                {
                    $result_code=1015;
                    $result_content='请求已过期';
                    $result['array']['api']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>""
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1012;
                $result_content='请求已过期';
                $result['array']['api']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
    }
}
else
{
    $result_code=10000;
    $result_content='无权调用接口';
    $result['array']['api']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>''
    );
    $result['exit']=1;
}
?>