<?php

#program/api/signin

//引入User类文件
include_class("User");
//实例化User类
$User=new User();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

//补全预处理参数
if(empty($_POST['app_id']))
    $_POST['app_id']="";
if(getPermission($_POST['app_id'],'api_signin')==='Y')
{
    if(empty($_GET['from']))
    {
        $result_code=1009;
        $result_content='from没有指定目标';
        $result['array']['api']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {
        if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
        {
            $result_code=1011;
            $result_content='必要参数为空';
            $result['array']['api']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
        else
        {
            //补齐不必要参数
            if(empty($_POST['time']))
                $_POST['time']='';
            if(empty($_POST['time_stamp']))
                $_POST['time_stamp']='';
            //取时间戳
            if(!empty($_POST['time_stamp']))
            $time=$_POST['time_stamp'];
            else
            $time=strtotime($_POST['time']);
            settype($time,'int');

            //判断时差是否在规定时间内
            if(time()-$time<=5*60&&time()-$time>=-(5*60))
            {
                if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
                {
                    //判断接口环境
                    if($_GET['from']==='app')
                    {
                        if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['imei']))
                        {
                            $result_code=1011;
                            $result_content='必要参数为空';
                            $result['array']['api']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            //app环境下参数正常时执行
                            //app签名
                            $server_variable=array(
                                'from'=>$_GET['from'],
                                'app_id'=>$_POST['app_id'],
                                'nonce'=>$_POST['nonce'],
                                'time'=>$_POST['time'],
                                'time_stamp'=>$_POST['time_stamp'],
                                'imei'=>$_POST['imei'],
                                'uuid'=>$_POST['uuid'],
                                'ukey'=>$_POST['ukey']
                            );
                            $server_sign='';
                            foreach($server_variable as $key=>$value)
                            {
                                $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                            }
                            $app_key=getAppkey($_POST['app_id']);
                            if(empty($app_key))
                            {
                                $result_code=1013;
                                $result_content='非法请求';
                                $result['array']['api']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>""
                                );
                                $result['exit']=1;
                            }
                            else
                            {
                                $server_sign.='&app_key='.getSignString($app_key);
                                $server_sign=md5($server_sign);
                                if($server_sign===$_POST['sign'])
                                {
                                    //app签名验证通过
                                    //设置必要参数
                                    $User->app_id=$_POST['app_id'];
                                    $User->database_object=$Database;
                                    //设置uuid和ukey
                                    $User->setUuid($_POST['uuid']);
                                    $User->setUkey($_POST['ukey']);
                                    //取当前时间戳
                                    $server_time_stamp=time();
                                    //验证用户是否登录成功
                                    if($User->getUserInfo())
                                    {
                                        //取当前日期,用于判断今天是否已签到
                                        $server_sign_time=date("Y-m-d",time());
                                        //取数据表名称
                                        $table_name=$Database->getTablename('temporary_signin_user');
                                        //删除过期的用户数据
                                        $sql_statement=$Database->object->prepare("DELETE FROM {$table_name} WHERE time_stamp<".(time()-7*24*60*60));
                                        $sql_statement->execute();
                                        //尝试查询
                                        $sql_statement=$Database->object->prepare("SELECT sign_time,time_stamp FROM {$table_name} WHERE app_id=:app_id AND uuid=:uuid AND user=:user AND sign_time=:sign_time ORDER BY id DESC LIMIT 0,1");
                                        $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                        $sql_statement->bindParam(':uuid',$_POST['uuid']);
                                        $sql_statement->bindParam(':user',$User->user_info['name']);
                                        $sql_statement->bindParam(':sign_time',$server_sign_time);
                                        $sql_statement->execute();
                                        $result_sql_temp=$sql_statement->fetch();
                                        if(isset($result_sql_temp['sign_time'])&&isset($result_sql_temp['time_stamp']))
                                        {
                                            //已经签到
                                            $result_code=1040;
                                            $result_content='用户已签到';
                                            $result['array']['api']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>''
                                            );
                                            $result['exit']=1;
                                        }
                                        else
                                        {
                                            //还未签到
                                            $sql_statement=$Database->object->prepare("INSERT INTO {$table_name}(app_id,time_stamp,user,uuid,sign_time) VALUES (:app_id,:time_stamp,:user,:uuid,:sign_time)");
                                            $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                            $sql_statement->bindParam(':time_stamp',$server_time_stamp);
                                            $sql_statement->bindParam(':user',$User->user_info['name']);
                                            $sql_statement->bindParam(':uuid',$_POST['uuid']);
                                            $sql_statement->bindParam(':sign_time',$server_sign_time);
                                            if($sql_statement->execute())
                                            {
                                                //签到数据记录成功,暂不判断是否存储成功
                                                $User->setUserIntegral(1,10);
                                                //刷新用户数据
                                                $User->getUserInfo();
                                                //取当前用户的积分
                                                $server_integral=$User->user_info['integral'];
                                                settype($server_integral,'int');
                                                //返回信息
                                                $result_code=0;
                                                $result_content='签到成功';
                                                $result['array']['api']=array(
                                                    'title'=>"签到成功",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>array(
                                                        'server_integral'=>$server_integral
                                                    )
                                                );
                                            }
                                            else
                                            {
                                                //签到数据记录失败
                                                $result_code=1018;
                                                $result_content='异常错误';
                                                $result['array']['api']=array(
                                                    'title'=>"失败",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>""
                                                );
                                                $result['exit']=1;
                                            }
                                        }
                                    }
                                    else
                                    {
                                        $result['array']['api']=$User->error_info['getUserInfo'];
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result_code=1014;
                                    $result_content='非法请求';
                                    $result['array']['api']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>$_POST['sign']
                                    );
                                    $result['exit']=1;
                                }
                            }
                        }
                    }
                    else
                    {
                        $result_code=1010;
                        $result_content='from指定目标不合法';
                        $result['array']['api']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>$_GET['from']
                        );
                        $result['exit']=1;
                    }
                }
                else
                {
                    $result_code=1015;
                    $result_content='请求已过期';
                    $result['array']['api']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>""
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1012;
                $result_content='请求已过期';
                $result['array']['api']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
    }
}
else
{
    $result_code=10000;
    $result_content='无权调用接口';
    $result['array']['api']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>''
    );
    $result['exit']=1;
}
?>