<?php

#program/application/admin_application_user_ibrary

//引入User类文件
include_class("User");
//引入Admin类文件
include_class("Admin");
//实例化User类
$User=new User();
//实例化Admin类
$Admin=new Admin();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

if(getPermission($_POST['app_id'],'application_api')==='Y')
{
    if(empty($_GET['from']))
    {
        $result_code=1009;
        $result_content='from没有指定目标';
        $result['array']['application']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {
        if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
        {
            $result_code=1011;
            $result_content='必要参数为空';
            $result['array']['application']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
        else
        {
            //补齐不必要参数
            if(empty($_POST['time']))
                $_POST['time']='';
            if(empty($_POST['time_stamp']))
                $_POST['time_stamp']='';
            //取时间戳
            if(!empty($_POST['time_stamp']))
            $time=$_POST['time_stamp'];
            else
            $time=strtotime($_POST['time']);
            settype($time,'int');

            //判断时差是否在规定时间内
            if(time()-$time<=5*60&&time()-$time>=-(5*60))
            {
                if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
                {
                    if($_GET['from']==='create')
                    {
                        if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['span_name']))
                        {
                            $result_code=1011;
                            $result_content='必要参数为空';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            //create环境下参数正常时执行
                            //create签名
                            $server_variable=array(
                                'from'=>$_GET['from'],
                                'app_id'=>$_POST['app_id'],
                                'nonce'=>$_POST['nonce'],
                                'time'=>$_POST['time'],
                                'time_stamp'=>$_POST['time_stamp'],
                                'uuid'=>$_POST['uuid'],
                                'ukey'=>$_POST['ukey'],
                                'span_name'=>$_POST['span_name']
                            );
                            $server_sign='';
                            foreach($server_variable as $key=>$value)
                            {
                                $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                            }
                            $app_key=getAppkey($_POST['app_id']);
                            $server_sign.='&app_key='.getSignString($app_key);
                            $server_sign=md5($server_sign);
                            if($server_sign===$_POST['sign'])
                            {
                                //create签名通过
                                //取当前时间戳
                                $server_time_stamp=time();
                                //设置必要参数
                                $User->app_id=$_POST['app_id'];
                                $User->database_object=$Database;
                                $Admin->app_id=$_POST['app_id'];
                                $Admin->database_object=$Database;
                                $Admin->uuid=$_POST['uuid'];
                                $Admin->admin_config=$main_config['admin_config'];
                                //设置uuid和ukey
                                $User->setUuid($_POST['uuid']);
                                $User->setUkey($_POST['ukey']);
                                //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                                $User->getUserInfo();
                                //验证用户是否登录成功
                                if($User->user_info['get'])
                                {
                                    $create_count=$Admin->getCreateCount();
                                    $create_user_library_count=$Admin->getCreateCountUserLibrary();
                                    if($create_user_library_count!=-1&&$create_count!=-1&&$create_user_library_count<$create_count+1)
                                    {
                                        //处理用户提交的数据
                                        $_POST['span_name']=mb_substr($_POST['span_name'],0,16);
                                        //写入创建的应用数据
                                        $table_name=$Database->getTablename('admin_api_user_library');
                                        $sql_statement=$Database->object->prepare("INSERT INTO {$table_name}(time_stamp,expired_time_stamp,span_id,span_name,uuid,app_id) VALUES (:time_stamp,:expired_time_stamp,:span_id,:span_name,:uuid,:app_id)");
                                        $expired_time_stamp=$server_time_stamp+30*24*60*60;
                                        $span_id=time().getRandomstring(22);
                                        $sql_statement->bindParam(':time_stamp',$server_time_stamp);
                                        $sql_statement->bindParam(':expired_time_stamp',$expired_time_stamp);
                                        $sql_statement->bindParam(':span_id',$span_id);
                                        $sql_statement->bindParam(':span_name',$_POST['span_name']);
                                        $sql_statement->bindParam(':uuid',$_POST['uuid']);
                                        $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                        if($sql_statement->execute())
                                        {
                                            //创建成功
                                            $result_code=0;
                                            $result_content='已成功创建用户库';
                                            $result['array']['application']=array(
                                                'title'=>"成功",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>array(
                                                    'uuid'=>$_POST['uuid'],
                                                    'span_id'=>$span_id,
                                                    'span_name'=>$_POST['span_name']
                                                )
                                            );
                                        }
                                        else
                                        {
                                            $result_code=1018;
                                            $result_content='异常错误';
                                            $result['array']['application']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>''
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result_code=1072;
                                        $result_content='创建总量已达上限';
                                        $result['array']['application']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>''
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result['array']['application']=$User->error_info['getUserInfo'];
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result_code=1014;
                                $result_content='非法请求';
                                $result['array']['application']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['sign']
                                );
                                $result['exit']=1;
                            }
                        }
                    }
                    else if($_GET['from']==='list')
                    {
                        if(empty($_POST['uuid'])||empty($_POST['ukey']))
                        {
                            $result_code=1011;
                            $result_content='必要参数为空';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            //list环境下参数正常时执行
                            //补全不必要参数
                            if(empty($_POST['page']))
                            {
                                $_POST['page']=1;
                            }
                            //list签名
                            $server_variable=array(
                                'from'=>$_GET['from'],
                                'app_id'=>$_POST['app_id'],
                                'nonce'=>$_POST['nonce'],
                                'time'=>$_POST['time'],
                                'time_stamp'=>$_POST['time_stamp'],
                                'uuid'=>$_POST['uuid'],
                                'ukey'=>$_POST['ukey'],
                                'page'=>$_POST['page']
                            );
                            $server_sign='';
                            foreach($server_variable as $key=>$value)
                            {
                                $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                            }
                            $app_key=getAppkey($_POST['app_id']);
                            $server_sign.='&app_key='.getSignString($app_key);
                            $server_sign=md5($server_sign);
                            if($server_sign===$_POST['sign'])
                            {
                                //list签名通过
                                //取当前时间戳
                                $server_time_stamp=time();
                                //设置必要参数
                                $User->app_id=$_POST['app_id'];
                                $User->database_object=$Database;
                                $Admin->app_id=$_POST['app_id'];
                                $Admin->database_object=$Database;
                                $Admin->uuid=$_POST['uuid'];
                                $Admin->admin_config=$main_config['admin_config'];
                                //设置uuid和ukey
                                $User->setUuid($_POST['uuid']);
                                $User->setUkey($_POST['ukey']);
                                //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                                $User->getUserInfo();
                                //验证用户是否登录成功
                                if($User->user_info['get'])
                                {
                                    $create_count=$Admin->getCreateCountUserLibrary();
                                    //获取数据信息
                                    $limit=($_POST['page']-1)*10;
                                    $table_name=$Database->getTablename('admin_api_user_library');
                                    $sql_statement=$Database->object->prepare("SELECT time_stamp,expired_time_stamp,span_id,span_name,app_id FROM {$table_name} WHERE uuid=:uuid ORDER BY id DESC LIMIT {$limit},20");
                                    $sql_statement->bindParam(':uuid',$_POST['uuid']);
                                    $sql_statement->execute();
                                    $temp_return_data=$sql_statement->fetchAll(PDO::FETCH_ASSOC);
                                    $result_code=0;
                                    $result_content='获取用户库列表成功';
                                    $result['array']['application']=array(
                                        'title'=>"成功",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>array(
                                            'count'=>$create_count,
                                            'maxCreateCount'=>$Admin->getCreateCount()+1,
                                            'page'=>ceil($create_count/20),
                                            'date'=>$temp_return_data
                                        )
                                    );
                                }
                                else
                                {
                                    $result['array']['application']=$User->error_info['getUserInfo'];
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result_code=1014;
                                $result_content='非法请求';
                                $result['array']['application']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['sign']
                                );
                                $result['exit']=1;
                            }
                        }
                    }
                    else if($_GET['from']==='info')
                    {
                        if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['span_id']))
                        {
                            $result_code=1011;
                            $result_content='必要参数为空';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            //info环境下参数正常时执行
                            //info签名
                            $server_variable=array(
                                'from'=>$_GET['from'],
                                'app_id'=>$_POST['app_id'],
                                'nonce'=>$_POST['nonce'],
                                'time'=>$_POST['time'],
                                'time_stamp'=>$_POST['time_stamp'],
                                'uuid'=>$_POST['uuid'],
                                'ukey'=>$_POST['ukey'],
                                'span_id'=>$_POST['span_id']
                            );
                            $server_sign='';
                            foreach($server_variable as $key=>$value)
                            {
                                $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                            }
                            $app_key=getAppkey($_POST['app_id']);
                            $server_sign.='&app_key='.getSignString($app_key);
                            $server_sign=md5($server_sign);
                            if($server_sign===$_POST['sign'])
                            {
                                //info签名通过
                                //取当前时间戳
                                $server_time_stamp=time();
                                //设置必要参数
                                $User->app_id=$_POST['app_id'];
                                $User->database_object=$Database;
                                $Admin->app_id=$_POST['app_id'];
                                $Admin->database_object=$Database;
                                $Admin->uuid=$_POST['uuid'];
                                $Admin->admin_config=$main_config['admin_config'];
                                //设置uuid和ukey
                                $User->setUuid($_POST['uuid']);
                                $User->setUkey($_POST['ukey']);
                                //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                                $User->getUserInfo();
                                //验证用户是否登录成功
                                if($User->user_info['get'])
                                {
                                    //获取信息并直接返回
                                    $user_library_info=$Admin->getUserLibraryInfo($_POST['span_id']);
                                    if($user_library_info)
                                    {
                                        $user_library_info['expired_time']=date("Y-m-d H:i:s",$user_library_info['expired_time_stamp']);
                                        $result_code=0;
                                        $result_content='获取应用信息成功';
                                        $result['array']['application']=array(
                                            'title'=>"成功",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>$user_library_info
                                        );
                                    }
                                    else
                                    {
                                        $result['array']['application']=$Admin->error_info['getUserLibraryInfo'];
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result['array']['application']=$User->error_info['getUserInfo'];
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result_code=1014;
                                $result_content='非法请求';
                                $result['array']['application']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['sign']
                                );
                                $result['exit']=1;
                            }
                        }
                    }
                    else if($_GET['from']==='renew')
                    {
                        if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['span_id']))
                        {
                            $result_code=1011;
                            $result_content='必要参数为空';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            //renew环境下参数正常时执行
                            //renew签名
                            $server_variable=array(
                                'from'=>$_GET['from'],
                                'app_id'=>$_POST['app_id'],
                                'nonce'=>$_POST['nonce'],
                                'time'=>$_POST['time'],
                                'time_stamp'=>$_POST['time_stamp'],
                                'uuid'=>$_POST['uuid'],
                                'ukey'=>$_POST['ukey'],
                                'span_id'=>$_POST['span_id'],
                            );
                            $server_sign='';
                            foreach($server_variable as $key=>$value)
                            {
                                $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                            }
                            $app_key=getAppkey($_POST['app_id']);
                            $server_sign.='&app_key='.getSignString($app_key);
                            $server_sign=md5($server_sign);
                            if($server_sign===$_POST['sign'])
                            {
                                //renew签名通过
                                //取当前时间戳
                                $server_time_stamp=time();
                                //设置必要参数
                                $User->app_id=$_POST['app_id'];
                                $User->database_object=$Database;
                                $Admin->app_id=$_POST['app_id'];
                                $Admin->database_object=$Database;
                                $Admin->uuid=$_POST['uuid'];
                                $Admin->admin_config=$main_config['admin_config'];
                                //设置uuid和ukey
                                $User->setUuid($_POST['uuid']);
                                $User->setUkey($_POST['ukey']);
                                //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                                $User->getUserInfo();
                                //验证用户是否登录成功
                                if($User->user_info['get'])
                                {
                                    //获取设置状态
                                    $user_library_info=$Admin->renewUserLibrary($_POST['span_id']);
                                    if($user_library_info)
                                    {
                                        $result_code=0;
                                        $result_content='用户库续费成功';
                                        $result['array']['application']=array(
                                            'title'=>"成功",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>'用户库已成功续费'
                                        );
                                    }
                                    else
                                    {
                                        $result['array']['application']=$Admin->error_info['renewUserLibrary'];
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result['array']['application']=$User->error_info['getUserInfo'];
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result_code=1014;
                                $result_content='非法请求';
                                $result['array']['application']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['sign']
                                );
                                $result['exit']=1;
                            }
                        }
                    }
                    else
                    {
                        $result_code=1010;
                        $result_content='from指定目标不合法';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>$_GET['from']
                        );
                        $result['exit']=1;
                    }
                }
                else
                {
                    $result_code=1015;
                    $result_content='请求已过期';
                    $result['array']['application']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>""
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1012;
                $result_content='请求已过期';
                $result['array']['application']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
    }
}
else
{
    $result_code=10000;
    $result_content='无权调用接口';
    $result['array']['application']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>''
    );
    $result['exit']=1;
}
?>