<?php

#program/application/file

//引入User类文件
include_class("User");
//实例化User类
$User=new User();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

if(empty($_GET['from']))
{
    $result_code=1009;
    $result_content='from没有指定目标';
    $result['array']['application']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>""
    );
    $result['exit']=1;
}
else
{
    if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
    {
        $result_code=1011;
        $result_content='必要参数为空';
        $result['array']['application']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {

        //补齐不必要参数
        if(empty($_POST['time']))
            $_POST['time']='';
        if(empty($_POST['time_stamp']))
            $_POST['time_stamp']='';
        //取时间戳
        if(!empty($_POST['time_stamp']))
        $time=$_POST['time_stamp'];
        else
        $time=strtotime($_POST['time']);
        settype($time,'int');

        //判断时差是否在规定时间内
        if(time()-$time<=5*60&&time()-$time>=-(5*60))
        {
            if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
            {
                //判断接口环境
                if($_GET['from']==='upload')
                {
                    if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['file_type']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //upload环境下参数正常时执行
                        //upload签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'uuid'=>$_POST['uuid'],
                            'ukey'=>$_POST['ukey'],
                            'file_type'=>$_POST['file_type']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        $server_sign.='&app_key='.getSignString($app_key);
                        $server_sign=md5($server_sign);
                        if($server_sign===$_POST['sign'])
                        {
                            //upload签名通过
                            if(empty($_FILES["file"])||$_FILES["file"]["error"]>0)
                            {
                                $result_code=1017;
                                $result_content='文件上传失败';
                                $result['array']['application']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>""
                                );
                                $result['exit']=1;
                            }
                            else
                            {
                                $file_size=filesize($_FILES["file"]["tmp_name"]);
                                if($file_size>5*1024*1024)
                                {
                                    $result_code=1046;
                                    $result_content='上传文件不合法';
                                    $result['array']['application']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                                else
                                {
                                    if(preg_match('/^[0-9a-zA-Z]{1,8}$/i',$_POST['file_type']))
                                    {
                                        //取当前时间戳
                                        $server_time_stamp=time();
                                        //设置必要参数
                                        $User->app_id=$_POST['app_id'];
                                        $User->database_object=$Database;
                                        //设置uuid和ukey
                                        $User->setUuid($_POST['uuid']);
                                        $User->setUkey($_POST['ukey']);
                                        //抛弃超出系统最大存储空间的数据
                                        $_POST['file_type']=mb_substr($_POST['file_type'],0,8);
                                        //验证用户是否登录成功
                                        if($User->getUserInfo())
                                        {
                                            $file_path="uploads/".(time().getRandomstring(12));
                                            move_uploaded_file($_FILES["file"]["tmp_name"],$file_path);
                                            //取数据表名称
                                            $table_name=$Database->getTablename('up_file');
                                            //取flid值
                                            $flid=getRandstringid();
                                            $sql_statement=$Database->object->prepare("INSERT INTO {$table_name}(time_stamp,uuid,app_id,flid,file_size,file_path,file_type) VALUES (:time_stamp,:uuid,:app_id,:flid,:file_size,:file_path,:file_type)");
                                            $sql_statement->bindParam(':time_stamp',$server_time_stamp);
                                            $sql_statement->bindParam(':uuid',$_POST['uuid']);
                                            $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                            $sql_statement->bindParam(':flid',$flid);
                                            $sql_statement->bindParam(':file_size',$file_size);
                                            $sql_statement->bindParam(':file_path',$file_path);
                                            $sql_statement->bindParam(':file_type',$_POST['file_type']);
                                            if($sql_statement->execute())
                                            {
                                                $result_code=0;
                                                $result_content='上传成功';
                                                $result['array']['application']=array(
                                                    'title'=>"成功",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>array(
                                                        "flid"=>$flid,
                                                        "size"=>$file_size,
                                                        "type"=>$_POST['file_type']
                                                    )
                                                );
                                            }
                                            else
                                            {
                                                $result_code=1018;
                                                $result_content='异常错误';
                                                $result['array']['application']=array(
                                                    'title'=>"失败",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>""
                                                );
                                                $result['exit']=1;
                                            }
                                        }
                                        else
                                        {
                                            $result['array']['application']=$User->error_info['getUserInfo'];
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result_code=1047;
                                        $result_content='文件类型不合法';
                                        $result['array']['application']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>$_POST['sign']
                                        );
                                        $result['exit']=1;
                                    }
                                }
                            }
                        }
                        else
                        {
                            $result_code=1014;
                            $result_content='非法请求';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>$_POST['sign']
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else if($_GET['from']==='get')
                {
                    if(empty($_POST['flid'])||empty($_POST['total']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //get环境下参数正常时执行
                        //get签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'flid'=>$_POST['flid'],
                            'total'=>$_POST['total']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        $server_sign.='&app_key='.getSignString($app_key);
                        $server_sign=md5($server_sign);
                        if($server_sign===$_POST['sign'])
                        {
                            //get签名通过
                            //取当前时间戳
                            $server_time_stamp=time();
                            $table_name=$Database->getTablename('up_file');
                            $sql_statement=$Database->object->prepare("SELECT time_stamp,uuid,flid,file_size,file_path,file_type FROM {$table_name} WHERE flid=:flid AND app_id=:app_id ORDER BY id DESC LIMIT 0,1");
                            $sql_statement->bindParam(':flid',$_POST['flid']);
                            $sql_statement->bindParam(':app_id',$_POST['app_id']);
                            $sql_statement->execute();
                            $result_sql_temp=$sql_statement->fetch();
                            if(isset($result_sql_temp['time_stamp']))
                            {
                                //存在文件纪录
                                settype($_POST['total'],"int");
                                if($_POST['total']>=1&&$_POST['total']<=3)
                                {
                                    //在允许的范围内
                                    $table_name=$Database->getTablename('download_file');
                                    $download_certificate=getRandstringid();
                                    $sql_statement=$Database->object->prepare("INSERT INTO {$table_name}(time_stamp,app_id,flid,file_path,file_type,download_certificate,download_count,download_total) VALUES (:time_stamp,:app_id,:flid,:file_path,:file_type,:download_certificate,0,:download_total)");
                                    $sql_statement->bindParam(':time_stamp',$server_time_stamp);
                                    $sql_statement->bindParam(':app_id',$_POST['app_id']);
                                    $sql_statement->bindParam(':flid',$_POST['flid']);
                                    $sql_statement->bindParam(':file_path',$result_sql_temp['file_path']);
                                    $sql_statement->bindParam(':file_type',$result_sql_temp['file_type']);
                                    $sql_statement->bindParam(':download_certificate',$download_certificate);
                                    $sql_statement->bindParam(':download_total',$_POST['total']);
                                    if($sql_statement->execute())
                                    {
                                        $result_code=0;
                                        $result_content='申请成功';
                                        $result['array']['application']=array(
                                            'title'=>"成功",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>array(
                                                "flid"=>$_POST['flid'],
                                                "size"=>$result_sql_temp['file_size'],
                                                "type"=>$result_sql_temp['file_type'],
                                                "uuid"=>$result_sql_temp['uuid'],
                                                "time_stamp"=>$result_sql_temp['time_stamp'],
                                                "time"=>date("Y-m-d H:i:s",$result_sql_temp['time_stamp']),
                                                "download_certificate"=>$download_certificate
                                            )
                                        );
                                    }
                                    else
                                    {
                                        $result_code=1018;
                                        $result_content='异常错误';
                                        $result['array']['application']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>""
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    //超出允许的范围
                                    $result_code=1049;
                                    $result_content='非法请求';
                                    $result['array']['application']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                //不存在文件纪录
                                $result_code=1048;
                                $result_content='找不到文件';
                                $result['array']['application']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['flid']
                                );
                                $result['exit']=1;
                            }
                        }
                        else
                        {
                            $result_code=1014;
                            $result_content='非法请求';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>$_POST['sign']
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else
                {
                    $result_code=1010;
                    $result_content='from指定目标不合法';
                    $result['array']['application']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>$_GET['from']
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1015;
                $result_content='请求已过期';
                $result['array']['application']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
        else
        {
            $result_code=1012;
            $result_content='请求已过期';
            $result['array']['application']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
    }
}
?>