<?php

#program/application/message

//引入User类文件
include_class("User");
//实例化User类
$User=new User();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

if(empty($_GET['from']))
{
    $result_code=1009;
    $result_content='from没有指定目标';
    $result['array']['application']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>""
    );
    $result['exit']=1;
}
else
{
    if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
    {
        $result_code=1011;
        $result_content='必要参数为空';
        $result['array']['application']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {

        //补齐不必要参数
        if(empty($_POST['time']))
            $_POST['time']='';
        if(empty($_POST['time_stamp']))
            $_POST['time_stamp']='';
        //取时间戳
        if(!empty($_POST['time_stamp']))
        $time=$_POST['time_stamp'];
        else
        $time=strtotime($_POST['time']);
        settype($time,'int');

        //判断时差是否在规定时间内
        if(time()-$time<=5*60&&time()-$time>=-(5*60))
        {
            if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
            {
                //判断接口环境
                if($_GET['from']==='send')
                {
                    if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['title'])||empty($_POST['content'])||empty($_POST['ruid']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //send环境下参数正常时执行
                        //send签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'uuid'=>$_POST['uuid'],
                            'ukey'=>$_POST['ukey'],
                            'title'=>$_POST['title'],
                            'content'=>$_POST['content'],
                            'ruid'=>$_POST['ruid']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        $server_sign.='&app_key='.getSignString($app_key);
                        $server_sign=md5($server_sign);
                        if($server_sign===$_POST['sign'])
                        {
                            //send签名通过
                            //取当前时间戳
                            $server_time_stamp=time();
                            //取原始数据值
                            $_POST['title']=base64_decode($_POST['title']);
                            $_POST['content']=base64_decode($_POST['content']);
                            //抛弃超过系统最大存储空间的数据
                            $_POST['title']=mb_substr($_POST['title'],0,32);
                            $_POST['content']=mb_substr($_POST['content'],0,1024*5);
                            //设置必要参数
                            $User->app_id=$_POST['app_id'];
                            $User->database_object=$Database;
                            //设置uuid和ukey
                            $User->setUuid($_POST['uuid']);
                            $User->setUkey($_POST['ukey']);
                            //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                            $User->getUserInfo();
                            //验证用户是否登录成功
                            if($User->user_info['get'])
                            {
                                $ruid_user_info=$User->getUuidInfo($_POST['ruid']);
                                if(isset($ruid_user_info['uuid']))
                                {
                                    if($User->sendUserMessage($_POST['title'],$_POST['content'],$_POST['uuid'],'',$_POST['ruid']))
                                    {
                                        $result_code=0;
                                        $result_content='发送成功';
                                        $result['array']['application']=array(
                                            'title'=>"成功",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>"消息已发送"
                                        );
                                    }
                                    else
                                    {
                                        $result['array']['application']=$User->error_info['sendUserMessage'];
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result['array']['application']=$User->error_info['getUuidInfo'];
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result['array']['application']=$User->error_info['getUserInfo'];
                                $result['exit']=1;
                            }    
                        }
                        else
                        {
                            $result_code=1014;
                            $result_content='非法请求';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>$_POST['sign']
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else
                {
                    $result_code=1010;
                    $result_content='from指定目标不合法';
                    $result['array']['application']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>$_GET['from']
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1015;
                $result_content='请求已过期';
                $result['array']['application']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
        else
        {
            $result_code=1012;
            $result_content='请求已过期';
            $result['array']['application']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
    }
}
?>