<?php

#program/application/tutorial_check

//引入User类文件
include_class("User");
//实例化User类
$User=new User();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

if(empty($_GET['from']))
{
    $result_code=1009;
    $result_content='from没有指定目标';
    $result['array']['application']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>""
    );
    $result['exit']=1;
}
else
{
    if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
    {
        $result_code=1011;
        $result_content='必要参数为空';
        $result['array']['application']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {

        //补齐不必要参数
        if(empty($_POST['time']))
            $_POST['time']='';
        if(empty($_POST['time_stamp']))
            $_POST['time_stamp']='';
        //取时间戳
        if(!empty($_POST['time_stamp']))
        $time=$_POST['time_stamp'];
        else
        $time=strtotime($_POST['time']);
        settype($time,'int');

        //判断时差是否在规定时间内
        if(time()-$time<=5*60&&time()-$time>=-(5*60))
        {
            if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
            {
                //判断接口环境
                if($_GET['from']==='chown')
                {
                    if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['ruid'])||empty($_POST['stateus'])||empty($_POST['tid']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //chown环境下参数正常时执行
                        //chown签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'uuid'=>$_POST['uuid'],
                            'ukey'=>$_POST['ukey'],
                            'ruid'=>$_POST['ruid'],
                            'stateus'=>$_POST['stateus'],
                            'tid'=>$_POST['tid']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        $server_sign.='&app_key='.getSignString($app_key);
                        $server_sign=md5($server_sign);
                        if($server_sign===$_POST['sign'])
                        {
                            //chown签名通过
                            //取当前时间戳
                            $server_time_stamp=time();
                            $table_name=$Database->getTablename('tutorial');
                            //设置必要参数
                            $User->app_id=$_POST['app_id'];
                            $User->database_object=$Database;
                            //设置uuid和ukey
                            $User->setUuid($_POST['uuid']);
                            $User->setUkey($_POST['ukey']);
                            //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                            $User->getUserInfo();
                            //验证用户是否登录成功
                            if($User->user_info['get'])
                            {
                                //定义允许修改教程审核者的用户组列表
                                $server_identification_group=array(
                                    '0',            //超管组
                                    '100','101'     //管理组
                                );
                                //判断用户组是否允许更改
                                if(in_array($User->user_info['identification'],$server_identification_group))
                                {
                                   //定义允许修改教程审核状态的用户组列表
                                    $server_identification_group=array(
                                        '0',            //超管组
                                        '100','101',    //管理组
                                        '1002','1003'   //教程审核组
                                    );
                                    //获取目标用户信息
                                    $ruid_user_info=$User->getUuidInfo($_POST['ruid']);
                                    if(isset($ruid_user_info['uuid']))
                                    {
                                        //目标用户存在
                                        //判断用户组是否允许更改
                                        if(in_array($ruid_user_info['identification'],$server_identification_group))
                                        {
                                            //判断允许修改的审核状态
                                            if($_POST['stateus']==='Y'||$_POST['stateus']==='N'||$_POST['stateus']==='R')
                                            {
                                                //查询数据是否存在
                                                $sql_statement=$Database->object->prepare("SELECT id,time_stamp FROM {$table_name} WHERE tid=:tid ORDER BY id DESC LIMIT 0,1");
                                                $sql_statement->bindParam(':tid',$_POST['tid']);
                                                $sql_statement->execute();
                                                $result_sql_temp=$sql_statement->fetch();
                                                if(isset($result_sql_temp['time_stamp']))
                                                {
                                                    //更新数据
                                                    $sql_statement=$Database->object->prepare("UPDATE {$table_name} SET ruid=:ruid,restatus=:restatus WHERE tid=:tid");
                                                    $sql_statement->bindParam(':ruid',$_POST['ruid']);
                                                    $sql_statement->bindParam(':restatus',$_POST['stateus']);
                                                    $sql_statement->bindParam(':tid',$_POST['tid']);
                                                    if($sql_statement->execute())
                                                    {
                                                        $result_code=0;
                                                        $result_content='修改成功';
                                                        $result['array']['application']=array(
                                                            'title'=>"成功",
                                                            'content'=>$result_content,
                                                            'code'=>$result_code,
                                                            'variable'=>"审核状态和审核用户已变更"
                                                        );
                                                    }
                                                    else
                                                    {
                                                        $result_code=1018;
                                                        $result_content='异常错误';
                                                        $result['array']['application']=array(
                                                            'title'=>"失败",
                                                            'content'=>$result_content,
                                                            'code'=>$result_code,
                                                            'variable'=>""
                                                        );
                                                        $result['exit']=1;
                                                    }
                                                }
                                                else
                                                {
                                                    $result_code=1052;
                                                    $result_content='资源已丢失';
                                                    $result['array']['application']=array(
                                                        'title'=>"失败",
                                                        'content'=>$result_content,
                                                        'code'=>$result_code,
                                                        'variable'=>''
                                                    );
                                                    $result['exit']=1;
                                                }
                                            }
                                            else
                                            {
                                                $result_code=1043;
                                                $result_content='错误的选择状态';
                                                $result['array']['application']=array(
                                                    'title'=>"失败",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>""
                                                );
                                                $result['exit']=1;
                                            }
                                        }
                                        else
                                        {
                                            $result_code=1054;
                                            $result_content='目标用户组无权限';
                                            $result['array']['application']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>$ruid_user_info['identification']
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result['array']['application']=$User->error_info['getUuidInfo'];
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result_code=1042;
                                    $result_content='用户组无权限';
                                    $result['array']['application']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result['array']['application']=$User->error_info['getUserInfo'];
                                $result['exit']=1;
                            }    
                        }
                        else
                        {
                            $result_code=1014;
                            $result_content='非法请求';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>$_POST['sign']
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else if($_GET['from']==='check')
                {
                    if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['stateus'])||empty($_POST['tid']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //check环境下参数正常时执行
                        //check签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'uuid'=>$_POST['uuid'],
                            'ukey'=>$_POST['ukey'],
                            'stateus'=>$_POST['stateus'],
                            'tid'=>$_POST['tid']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        $server_sign.='&app_key='.getSignString($app_key);
                        $server_sign=md5($server_sign);
                        if($server_sign===$_POST['sign'])
                        {
                            //check签名通过
                            //取当前时间戳
                            $server_time_stamp=time();
                            //设置必要参数
                            $User->app_id=$_POST['app_id'];
                            $User->database_object=$Database;
                            //设置uuid和ukey
                            $User->setUuid($_POST['uuid']);
                            $User->setUkey($_POST['ukey']);
                            //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                            $User->getUserInfo();
                            //验证用户是否登录成功
                            if($User->user_info['get'])
                            {
                                //定义允许修改审核状态的用户组列表
                                $server_identification_group=array(
                                    '0',            //超管组
                                    '100','101',    //管理组
                                    '1002','1003'   //教程审核组
                                );
                                if(in_array($User->user_info['identification'],$server_identification_group))
                                {
                                    $table_name=$Database->getTablename('tutorial');
                                    if($_POST['stateus']==='Y'||$_POST['stateus']==='N')
                                    {
                                        //查询数据是否存在
                                        $sql_statement=$Database->object->prepare("SELECT id,time_stamp FROM {$table_name} WHERE tid=:tid AND ruid=:ruid AND restatus='R' ORDER BY id DESC LIMIT 0,1");
                                        $sql_statement->bindParam(':tid',$_POST['tid']);
                                        $sql_statement->bindParam(':ruid',$_POST['uuid']);
                                        $sql_statement->execute();
                                        $result_sql_temp=$sql_statement->fetch();
                                        if(isset($result_sql_temp['time_stamp']))
                                        {
                                            //更新数据
                                            $sql_statement=$Database->object->prepare("UPDATE {$table_name} SET restatus=:restatus WHERE tid=:tid AND ruid=:ruid");
                                            $sql_statement->bindParam(':tid',$_POST['tid']);
                                            $sql_statement->bindParam(':ruid',$_POST['uuid']);
                                            $sql_statement->bindParam(':restatus',$_POST['stateus']);
                                            if($sql_statement->execute())
                                            {
                                                $result_code=0;
                                                $result_content='修改成功';
                                                $result['array']['application']=array(
                                                    'title'=>"成功",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>"审核状态已更改"
                                                );
                                            }
                                            else
                                            {
                                                $result_code=1018;
                                                $result_content='异常错误';
                                                $result['array']['application']=array(
                                                    'title'=>"失败",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>""
                                                );
                                                $result['exit']=1;
                                            }
                                        }
                                        else
                                        {
                                            $result_code=1052;
                                            $result_content='资源已丢失';
                                            $result['array']['application']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>''
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result_code=1043;
                                        $result_content='错误的选择状态';
                                        $result['array']['application']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>""
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result_code=1042;
                                    $result_content='用户组无权限';
                                    $result['array']['application']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result['array']['application']=$User->error_info['getUserInfo'];
                                $result['exit']=1;
                            }
                        }
                        else
                        {
                            $result_code=1014;
                            $result_content='非法请求';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>$_POST['sign']
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else if($_GET['from']==='get')
                {
                    if(empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['tid']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['application']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //get环境下参数正常时执行
                        //get签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'uuid'=>$_POST['uuid'],
                            'ukey'=>$_POST['ukey'],
                            'tid'=>$_POST['tid']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        $server_sign.='&app_key='.getSignString($app_key);
                        $server_sign=md5($server_sign);
                        if($server_sign===$_POST['sign'])
                        {
                            //get签名通过
                            //取当前时间戳
                            $server_time_stamp=time();
                            //设置必要参数
                            $User->app_id=$_POST['app_id'];
                            $User->database_object=$Database;
                            //设置uuid和ukey
                            $User->setUuid($_POST['uuid']);
                            $User->setUkey($_POST['ukey']);
                            //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                            $User->getUserInfo();
                            //验证用户是否登录成功
                            if($User->user_info['get'])
                            {
                                //定义允许修改审核状态的用户组列表
                                $server_identification_group=array(
                                    '0',            //超管组
                                    '100','101',    //管理组
                                    '1002','1003'   //教程审核组
                                );
                                if(in_array($User->user_info['identification'],$server_identification_group))
                                {
                                    $table_name=$Database->getTablename('tutorial');
                                    //查询数据是否存在
                                    $sql_statement=$Database->object->prepare("SELECT id,time_stamp FROM {$table_name} WHERE tid=:tid AND restatus='U' ORDER BY id DESC LIMIT 0,1");
                                    $sql_statement->bindParam(':tid',$_POST['tid']);
                                    $sql_statement->execute();
                                    $result_sql_temp=$sql_statement->fetch();
                                    if(isset($result_sql_temp['time_stamp']))
                                    {
                                        //更新数据
                                        $sql_statement=$Database->object->prepare("UPDATE {$table_name} SET restatus='R',ruid=:ruid WHERE tid=:tid");
                                        $sql_statement->bindParam(':tid',$_POST['tid']);
                                        $sql_statement->bindParam(':ruid',$_POST['uuid']);
                                        if($sql_statement->execute())
                                        {
                                            $result_code=0;
                                            $result_content='修改成功';
                                            $result['array']['application']=array(
                                                'title'=>"成功",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>"已成功夺取审核权限"
                                            );
                                        }
                                        else
                                        {
                                            $result_code=1018;
                                            $result_content='异常错误';
                                            $result['array']['application']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>""
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result_code=1052;
                                        $result_content='资源已丢失';
                                        $result['array']['application']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>''
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result_code=1042;
                                    $result_content='用户组无权限';
                                    $result['array']['application']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result['array']['application']=$User->error_info['getUserInfo'];
                                $result['exit']=1;
                            }
                        }
                        else
                        {
                            $result_code=1014;
                            $result_content='非法请求';
                            $result['array']['application']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>$_POST['sign']
                            );
                            $result['exit']=1;
                        }
                    }
                }
                else
                {
                    $result_code=1010;
                    $result_content='from指定目标不合法';
                    $result['array']['application']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>$_GET['from']
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1015;
                $result_content='请求已过期';
                $result['array']['application']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
        else
        {
            $result_code=1012;
            $result_content='请求已过期';
            $result['array']['application']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
    }
}
?>