<?php

#program/qq/group_push

//补全预处理参数
if(empty($_POST['app_id']))
    $_POST['app_id']="";
if(getPermission($_POST['app_id'],'qq_api')==='Y')
{
    if(empty($_GET['from']))
    {
        $result_code=1009;
        $result_content='from没有指定目标';
        $result['array']['qq']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {
        if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
        {
            $result_code=1011;
            $result_content='必要参数为空';
            $result['array']['qq']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
        else
        {
            //补齐不必要参数
            if(empty($_POST['time']))
                $_POST['time']='';
            if(empty($_POST['time_stamp']))
                $_POST['time_stamp']='';
            //取时间戳
            if(!empty($_POST['time_stamp']))
            $time=$_POST['time_stamp'];
            else
            $time=strtotime($_POST['time']);
            settype($time,'int');

            //判断时差是否在规定时间内
            if(time()-$time<=5*60&&time()-$time>=-(5*60))
            {
                if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
                {
                    if($_GET['from']==='tutorial')
                    {
                        //tutorial环境下参数正常时执行
                        //tutorial签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        if(empty($app_key))
                        {
                            $result_code=1013;
                            $result_content='非法请求';
                            $result['array']['qq']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            $server_sign.='&app_key='.getSignString($app_key);
                            $server_sign=md5($server_sign);
                            if($server_sign===$_POST['sign'])
                            {
                                //tutorial签名验证通过
                                //取当前时间戳
                                $server_time_stamp=time();
                                $table_name=$Database->getTablename('tutorial');
                                $sql_statement=$Database->object->prepare("SELECT id,restatus,nickname,uuid,tid,like_number,reward_number,watch_number,time_stamp,title,content FROM {$table_name} WHERE restatus='Y' AND qq_push='N' ORDER BY id ASC LIMIT 0,1");
                                $sql_statement->execute();
                                $result_sql_temp=$sql_statement->fetch();
                                if(isset($result_sql_temp['time_stamp']))
                                {
                                    //获取模板
                                    $template_path="template/qq_push/group_push_tutorial.txt";
                                    if(is_file($template_path))
                                    {
                                        $push_content=file_get_contents($template_path);
                                        //绑定模板变量
                                        $content_array=array(
                                            "\${id}"=>$result_sql_temp['id'],
                                            "\${restatus}"=>$result_sql_temp['restatus'],
                                            "\${nickname}"=>$result_sql_temp['nickname'],
                                            "\${uuid}"=>$result_sql_temp['uuid'],
                                            "\${tid}"=>$result_sql_temp['tid'],
                                            "\${like_number}"=>$result_sql_temp['like_number'],
                                            "\${reward_number}"=>$result_sql_temp['reward_number'],
                                            "\${watch_number}"=>$result_sql_temp['watch_number'],
                                            "\${time_stamp}"=>$result_sql_temp['time_stamp'],
                                            "\${title}"=>$result_sql_temp['title'],
                                            "\${date}"=>date("Y-m-d H:i:s",$result_sql_temp['time_stamp']),
                                            "\${organization}"=>$main_config['organization_config']['name'],
                                            "\${url}"=>"{$main_config['html_config']['protocol']}://{$main_config['html_config']['domain']}/?class=tutorial&tid={$result_sql_temp['tid']}",
                                            "\${content}"=>mb_strlen($result_sql_temp['content'])>32?mb_substr($result_sql_temp['content'],0,32)."...":$result_sql_temp['content'],
                                            "{\$}"=>'$'
                                        );
                                        foreach($content_array as $key=>$value)
                                        {
                                            $push_content=str_replace($key,$value,$push_content);
                                        }
                                        //去掉推送标识,不验证是否成功
                                        $sql_statement=$Database->object->prepare("UPDATE {$table_name} SET qq_push='Y' WHERE tid=:tid");
                                        $sql_statement->bindParam(':tid',$result_sql_temp['tid']);
                                        $sql_statement->execute();
                                        //输出结果
                                        $result_code=0;
                                        $result_content='获取成功';
                                        $result['array']['qq']=array(
                                            'title'=>"成功",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>$push_content
                                        );
                                    }
                                    else
                                    {
                                        $result_code=1056;
                                        $result_content='模板缺失';
                                        $result['array']['qq']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>""
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result_code=1055;
                                    $result_content='暂无可用推荐资源';
                                    $result['array']['qq']=array(
                                        'title'=>"失败",
                                        'content'=>$result_content,
                                        'code'=>$result_code,
                                        'variable'=>""
                                    );
                                    $result['exit']=1;
                                }
                            }
                            else
                            {
                                $result_code=1014;
                                $result_content='非法请求';
                                $result['array']['qq']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['sign']
                                );
                                $result['exit']=1;
                            }
                        }
                    }
                    else
                    {
                        $result_code=1010;
                        $result_content='from指定目标不合法';
                        $result['array']['qq']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>$_GET['from']
                        );
                        $result['exit']=1;
                    }
                }
                else
                {
                    $result_code=1015;
                    $result_content='请求已过期';
                    $result['array']['qq']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>""
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1012;
                $result_content='请求已过期';
                $result['array']['qq']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
    }
}
else
{
    $result_code=10000;
    $result_content='无权调用接口';
    $result['array']['qq']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>''
    );
    $result['exit']=1;
}
?>