<?php

#program/system/report

//引入User类文件
include_class("User");
//实例化User类
$User=new User();
//同步参数
$User->setStartSalt($main_config['user_info']['start_salt']);
$User->setEndSalt($main_config['user_info']['end_salt']);

if(empty($_GET['from']))
{
    $result_code=1009;
    $result_content='from没有指定目标';
    $result['array']['system']=array(
        'title'=>"失败",
        'content'=>$result_content,
        'code'=>$result_code,
        'variable'=>""
    );
    $result['exit']=1;
}
else
{
    if(empty($_POST['app_id'])||empty($_POST['sign'])||empty($_POST['nonce'])||!(!empty($_POST['time'])||!empty($_POST['time_stamp'])))
    {
        $result_code=1011;
        $result_content='必要参数为空';
        $result['array']['system']=array(
            'title'=>"失败",
            'content'=>$result_content,
            'code'=>$result_code,
            'variable'=>""
        );
        $result['exit']=1;
    }
    else
    {

        //补齐不必要参数
        if(empty($_POST['time']))
            $_POST['time']='';
        if(empty($_POST['time_stamp']))
            $_POST['time_stamp']='';
        //取时间戳
        if(!empty($_POST['time_stamp']))
        $time=$_POST['time_stamp'];
        else
        $time=strtotime($_POST['time']);
        settype($time,'int');

        //判断时差是否在规定时间内
        if(time()-$time<=5*60&&time()-$time>=-(5*60))
        {
            if(getConce($_POST['nonce'],$_POST['sign'],$_POST['app_id']))
            {
                //判断接口环境
                if($_GET['from']==='take')
                {
                    if(empty($_POST['id'])||empty($_POST['uuid'])||empty($_POST['ukey'])||empty($_POST['status']))
                    {
                        $result_code=1011;
                        $result_content='必要参数为空';
                        $result['array']['system']=array(
                            'title'=>"失败",
                            'content'=>$result_content,
                            'code'=>$result_code,
                            'variable'=>""
                        );
                        $result['exit']=1;
                    }
                    else
                    {
                        //take环境下参数正常时执行
                        //take签名
                        $server_variable=array(
                            'from'=>$_GET['from'],
                            'app_id'=>$_POST['app_id'],
                            'nonce'=>$_POST['nonce'],
                            'time'=>$_POST['time'],
                            'time_stamp'=>$_POST['time_stamp'],
                            'id'=>$_POST['id'],
                            'uuid'=>$_POST['uuid'],
                            'ukey'=>$_POST['ukey'],
                            'status'=>$_POST['status']
                        );
                        $server_sign='';
                        foreach($server_variable as $key=>$value)
                        {
                            $server_sign.=$server_sign?"&{$key}=".getSignString($value):"{$key}=".getSignString($value);
                        }
                        $app_key=getAppkey($_POST['app_id']);
                        if(empty($app_key))
                        {
                            $result_code=1013;
                            $result_content='非法请求';
                            $result['array']['system']=array(
                                'title'=>"失败",
                                'content'=>$result_content,
                                'code'=>$result_code,
                                'variable'=>""
                            );
                            $result['exit']=1;
                        }
                        else
                        {
                            $server_sign.='&app_key='.getSignString($app_key);
                            $server_sign=md5($server_sign);
                            if($server_sign===$_POST['sign'])
                            {
                                //take签名通过
                                //取当前时间戳
                                $server_time_stamp=time();
                                //设置必要参数
                                $User->app_id=$_POST['app_id'];
                                $User->database_object=$Database;
                                //设置uuid和ukey
                                $User->setUuid($_POST['uuid']);
                                $User->setUkey($_POST['ukey']);
                                //获取用户信息(直接判断是否登录无法验证用户是否处于激活状态)
                                $User->getUserInfo();
                                //验证用户是否登录成功
                                if($User->user_info['get'])
                                {
                                    //定义允许更改举报状态的用户组列表
                                    $server_identification_group=array(
                                        '0',            //超管组
                                        '100','101',    //管理组
                                        '1000','1001'   //举报审核组
                                    );
                                    //判断用户组是否允许更改
                                    if(in_array($User->user_info['identification'],$server_identification_group))
                                    {
                                        //允许更改(该接口对其提交的状态值不关心,这里手残写了,方便以后复制的)
                                        if($_POST['status']==='Y'||$_POST['status']==='N')
                                        {
                                            //取数据表名称
                                            $table_name=$Database->getTablename('api_report_info_app');
                                            //尝试查询举报数据是否存在
                                            $sql_statement=$Database->object->prepare("SELECT restatus FROM {$table_name} WHERE id=:id ORDER BY id DESC LIMIT 0,1");
                                            $sql_statement->bindParam(':id',$_POST['id']);
                                            $sql_statement->execute();
                                            $result_sql_temp=$sql_statement->fetch();
                                            if(isset($result_sql_temp['restatus'])&&$result_sql_temp['restatus']==='U')
                                            {
                                                //修改举报状态
                                                $sql_statement=$Database->object->prepare("UPDATE {$table_name} SET restatus='R',deal_uuid=:deal_uuid WHERE id=:id");
                                                $sql_statement->bindParam(':deal_uuid',$_POST['uuid']);
                                                $sql_statement->bindParam(':id',$_POST['id']);
                                                if($sql_statement->execute())
                                                {
                                                    $result_code=0;
                                                    $result_content='已接取举报信息';
                                                    $result['array']['system']=array(
                                                        'title'=>"成功",
                                                        'content'=>$result_content,
                                                        'code'=>$result_code,
                                                        'variable'=>"请认真审核"
                                                    );
                                                }
                                                else
                                                {
                                                    $result_code=1018;
                                                    $result_content='异常错误';
                                                    $result['array']['system']=array(
                                                        'title'=>"失败",
                                                        'content'=>$result_content,
                                                        'code'=>$result_code,
                                                        'variable'=>""
                                                    );
                                                    $result['exit']=1;
                                                }
                                            }
                                            else
                                            {
                                                $result_code=1044;
                                                $result_content='非法请求';
                                                $result['array']['system']=array(
                                                    'title'=>"失败",
                                                    'content'=>$result_content,
                                                    'code'=>$result_code,
                                                    'variable'=>''
                                                );
                                                $result['exit']=1;
                                            }
                                        }
                                        else
                                        {
                                            $result_code=1043;
                                            $result_content='错误的选择状态';
                                            $result['array']['system']=array(
                                                'title'=>"失败",
                                                'content'=>$result_content,
                                                'code'=>$result_code,
                                                'variable'=>''
                                            );
                                            $result['exit']=1;
                                        }
                                    }
                                    else
                                    {
                                        $result_code=1042;
                                        $result_content='用户组无权限';
                                        $result['array']['system']=array(
                                            'title'=>"失败",
                                            'content'=>$result_content,
                                            'code'=>$result_code,
                                            'variable'=>''
                                        );
                                        $result['exit']=1;
                                    }
                                }
                                else
                                {
                                    $result['array']['system']=$User->error_info['getUserInfo'];
                                    $result['exit']=1;
                                }    
                            }
                            else
                            {
                                $result_code=1014;
                                $result_content='非法请求';
                                $result['array']['system']=array(
                                    'title'=>"失败",
                                    'content'=>$result_content,
                                    'code'=>$result_code,
                                    'variable'=>$_POST['sign']
                                );
                                $result['exit']=1;
                            }
                        }
                    }
                }
                else
                {
                    $result_code=1010;
                    $result_content='from指定目标不合法';
                    $result['array']['system']=array(
                        'title'=>"失败",
                        'content'=>$result_content,
                        'code'=>$result_code,
                        'variable'=>$_GET['from']
                    );
                    $result['exit']=1;
                }
            }
            else
            {
                $result_code=1015;
                $result_content='请求已过期';
                $result['array']['system']=array(
                    'title'=>"失败",
                    'content'=>$result_content,
                    'code'=>$result_code,
                    'variable'=>""
                );
                $result['exit']=1;
            }
        }
        else
        {
            $result_code=1012;
            $result_content='请求已过期';
            $result['array']['system']=array(
                'title'=>"失败",
                'content'=>$result_content,
                'code'=>$result_code,
                'variable'=>""
            );
            $result['exit']=1;
        }
    }
}
?>